strictness: none
test-warnings: true
doc-warnings: true
max-line-length: 99

ignore-paths:
  - tests

pyroma:
  run: true
  disable:
    - PYR15

pep8:
  disable:
    - E701

pep257:
  disable:
    - D104
    - D202
    - D203
    - D212
    - D213
